### ISSUE TITLE
Objectives

### ISSUE THREAD

**Issue by mahimafire1234** [Drone-project-RWP/Documentation#1]
- [x] Complete by Friday
- [x]  Write objectives for our project @rajivsunar07

**Comment by rajivsunar07** [comment]
[Objectives of the project.docx](https://github.com/Drone-project-RWP/Documentation/files/5878139/Objectives.of.the.project.docx)
Completed

**Comment by rajivsunar07** [comment]
> * [x]  Complete by Friday
> * [x]   Write aims and objectives for our project @rajivsunar07

**Comment by mahimafire1234** [comment]
Youtube tutorials
